# Generated by Django 4.0 on 2024-04-03 22:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='mcfcarbrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=100)),
                ('idbs', models.IntegerField()),
                ('creationdate', models.DateField()),
                ('changedate', models.DateField()),
                ('mcfcode', models.CharField(default='id', max_length=100)),
            ],
            options={
                'db_table': 'mcfcarbrand',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='mcfcarmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=100)),
                ('idbs', models.IntegerField()),
                ('creationdate', models.DateField()),
                ('changedate', models.DateField()),
                ('mcfcode', models.CharField(default='id', max_length=100)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto_cc.mcfcarbrand')),
                ('changeauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_mcfcarmodels', to='avto_cc.user')),
                ('creationauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mcfcarmodels', to='avto_cc.user')),
            ],
            options={
                'db_table': 'mcfcarmodel',
            },
        ),
        migrations.CreateModel(
            name='mcfcarcolor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Name', models.CharField(max_length=100)),
                ('idbs', models.IntegerField()),
                ('creationdate', models.DateField()),
                ('changedate', models.DateField()),
                ('isdeleted', models.BooleanField()),
                ('changeauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_mcfcarcolors', to='avto_cc.user')),
                ('creationauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mcfcarcolors', to='avto_cc.user')),
            ],
            options={
                'db_table': 'mcfcarcolor',
            },
        ),
        migrations.AddField(
            model_name='mcfcarbrand',
            name='changeauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_mcfcarbrands', to='avto_cc.user'),
        ),
        migrations.AddField(
            model_name='mcfcarbrand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto_cc.country'),
        ),
        migrations.AddField(
            model_name='mcfcarbrand',
            name='creationauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mcfcarbrands', to='avto_cc.user'),
        ),
    ]
