# Generated by Django 4.0 on 2024-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto_cc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcfcarmodel',
            name='carbrand',
        ),
        migrations.AlterField(
            model_name='mcfcarcolor',
            name='uid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='mcfcarmodel',
            name='uid',
            field=models.UUIDField(),
        ),
    ]
