# Generated by Django 4.0 on 2024-04-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto_cc', '0002_remove_mcfcarmodel_carbrand_alter_mcfcarcolor_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcfcarmodel',
            name='carbrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avto_cc.mcfcarbrand'),
            preserve_default=False,
        ),
    ]
