# Generated by Django 4.0 on 2024-04-24 06:48

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=geoposition.fields.GeopositionField(default='43.23269713756249,76.91163003444672', max_length=42, null=True),
        ),
    ]
